### ISSUE TITLE
Getting warning "9 vulnerabilities (7 moderate, 2 high)"

### ISSUE THREAD

**Issue by albert-massey** [QasimWani/leetcode#1]
Hi there,

I am trying to set this extension up. I am getting the following warning about vulnerabilities. How can I fix it?

![Screenshot from 2021-12-04 15-19-22](https://user-images.githubusercontent.com/6724613/144727608-4b1e1dca-bd90-4884-a0b5-3f29756b0015.png)

**Comment by QasimWani** [comment]
hey there, u can ignore those since most of those packages are probably linting related. we don't make use of any packages in the extension itself.

**Comment by albert-massey** [comment]
Works like magic! Thank you for creating this.
